#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Rahul Rajan
url: ''
baseurl: '/rahul96rajan.github.io' #change it according to your repository name
description: Rahul Rajan's personal webpage
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: turquoise # blue turquoise green berry orange ceramic

# Tracker
analytics: UA-11391792-7



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
# compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false

#theme: jekyll-theme-cayman
